// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhIi-ChGlWvo8LFiZBx2KioLgbA3EgEKM',
    appId: '1:556837801740:web:515335b1595b45617d4329',
    messagingSenderId: '556837801740',
    projectId: 'fir-learn-a4b74',
    authDomain: 'fir-learn-a4b74.firebaseapp.com',
    storageBucket: 'fir-learn-a4b74.firebasestorage.app',
    measurementId: 'G-TTZNV57RKK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBaYOEsujbPtUAr8_uW90_oxbhatvB-DA',
    appId: '1:556837801740:android:b0c2970451b7cffd7d4329',
    messagingSenderId: '556837801740',
    projectId: 'fir-learn-a4b74',
    storageBucket: 'fir-learn-a4b74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCjmjoA7EJqHxx8gufVERSweg0PSNY8qo',
    appId: '1:556837801740:ios:021fdd54dadb71717d4329',
    messagingSenderId: '556837801740',
    projectId: 'fir-learn-a4b74',
    storageBucket: 'fir-learn-a4b74.firebasestorage.app',
    iosBundleId: 'com.example.flutterLearn',
  );
}
